#!/bin/bash
#      create_manual_clamscan
#     written from ‘initial setup’ 2016-02-19
#
#
#       2021-01-17      - added server name and used gmailSMTP instead

#
#
SCAN_DIR="/home/"                                               ;
LOG_FILE="/var/log/clamav/manual_clamscan.log"                  ;
LOG_FILE_TMP="/var/log/clamav/manual_clamscan_tmp.log"          ;
VERSION=$(/usr/local/bash/getLinuxVersion.bsh)                  ;       ## 2021-01-17
RESULTS=$(grep 'Infected files:'  $LOG_FILE_TMP ;       )       ;
EMAIL_SUBJECT="${VERSION} ${RESULTS}"                           ;
echo 'Starting clam scan!'                                      ;
date;
/usr/bin/clamscan --infected --recursive $SCAN_DIR > $LOG_FILE_TMP      ;
cat $LOG_FILE_TMP |  mailx -v    -A  gmailSMTP-noreply  -r 'noreply@comptonpeslonline.com'  -s "${EMAIL_SUBJECT}"  mark@edwardsmark.com  ;
cat $LOG_FILE_TMP >> $LOG_FILE ;
date;
#     written from ‘initial setup’ 2016-02-19
exit;
